name: "helm-git"
version: "1.0.1"
description: |-
  Let's you use private gitlab repositories easily
downloaders:
- command: "getfile.sh"
  protocols:
    - "gitlab"
    - "github"
    - "us-south.git.cloud.ibm.com"
